---
- hosts: atgninja
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install a .deb package from the internet
      ansible.builtin.apt:
        deb: https://atgfw.com/appliedtechnologygroupincmain-6.0.1816-installer-x86-64.deb
