- name: Add port 22 rule only to firewalls missing it
  hosts: localhost
  gather_facts: false
  collections:
    - community.digitalocean

  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    ssh_rule:
      protocol: tcp
      port_range: "22"
      source_addresses:
        - "0.0.0.0/0"
        - "::/0"

  tasks:

    - name: Get all DigitalOcean firewalls
      community.digitalocean.digital_ocean_firewall_info:
        oauth_token: "{{ do_token }}"
      register: firewalls_info

    - name: Filter firewalls without SSH rule
      set_fact:
        firewalls_needing_ssh: >-
          {{
            firewalls_info.data | selectattr("inbound_rules", "defined") | select(
              lambda fw: (
                fw.inbound_rules | map(attribute='ports') | list
                | select(
                    'match',
                    '^22$|^22-[0-9]+$|^[0-9]+-22$|^[0-9]+-[0-9]+$'
                  )
                | list | length == 0
              )
            ) | list
          }}

    - name: Add SSH rule to firewalls missing it
      community.digitalocean.digital_ocean_firewall:
        oauth_token: "{{ do_token }}"
        state: present
        name: "{{ item.name }}"
        inbound_rules: "{{ item.inbound_rules + [ssh_rule] }}"
        outbound_rules: "{{ item.outbound_rules }}"
        droplet_ids: "{{ item.droplet_ids }}"
      loop: "{{ firewalls_needing_ssh }}"
      loop_control:
        label: "{{ item.name }}"
