---
- name: Add SSH rule to DigitalOcean firewalls that lack it
  hosts: localhost
  gather_facts: false
  collections:
    - community.digitalocean

  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    ssh_rule:
      protocol: tcp
      port_range: "22"
      source_addresses:
        - '161.35.133.150/32'
        - '208.103.13.38/30'
        - '173.165.98.241/29'
        - '138.197.62.57/32'

  tasks:
    - name: Get all DigitalOcean firewalls
      community.digitalocean.digital_ocean_firewall_info:
        oauth_token: "{{ do_token }}"
      register: firewalls_info

    - name: Initialize list of firewalls missing SSH
      set_fact:
        firewalls_missing_ssh: []

    - name: Add firewalls that don't allow port 22 to list
      set_fact:
        firewalls_missing_ssh: "{{ firewalls_missing_ssh + [item] }}"
      loop: "{{ firewalls_info.data }}"
      when: >
        item.inbound_rules | selectattr('protocol', 'equalto', 'tcp') |
        selectattr('ports', 'defined') |
        selectattr('ports', 'search', '(^22$|^22-[0-9]+$|^[0-9]+-22$|^[0-9]+-[0-9]+$)') |
        list | length == 0
      loop_control:
        label: "{{ item.name }}"

    - name: Process each firewall needing SSH
      include_tasks: process_firewall.yml
      loop: "{{ firewalls_missing_ssh }}"
      loop_control:
        loop_var: "firewall"
        label: "{{ firewall.name }}"
