---
- name: Create one DigitalOcean firewall and attach all droplets
  hosts: localhost
  gather_facts: false
  collections:
    - community.digitalocean

  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    firewall_name: "atg-ssh-firewall"
    ssh_rule:
      protocol: tcp
      port_range: "22"
      source_addresses:
        - "161.35.133.150/32"
        - "208.103.13.38/30"
        - "173.165.98.241/29"
        - "138.197.62.57/32"

  tasks:

    - name: Get all droplets
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ do_token }}"
      register: droplet_info

    - name: Extract droplet IDs
      set_fact:
        droplet_ids: "{{ droplet_info.data | map(attribute='id') | list }}"

    - name: Create or update firewall
      community.digitalocean.digital_ocean_firewall:
        oauth_token: "{{ do_token }}"
        state: present
        name: "{{ firewall_name }}"
        inbound_rules:
          - protocol: "{{ ssh_rule.protocol }}"
            port_range: "{{ ssh_rule.port_range }}"
            source_addresses: "{{ ssh_rule.source_addresses }}"
        droplet_ids: "{{ droplet_ids }}"
