# Allows tcp connections to port 22 (SSH) from specific sources

# The firewall rules will be applied to any droplets with the tag "sample"

- name: Allow SSH access from ansible
  hosts: all
  gather_facts: false
  tasks:
  - name: Create Firewall
    local_action: 
      module: community.digitalocean.digital_ocean_firewall
      name: AWX
      state: present
      inbound_rules:
      - protocol: "tcp"
        ports: "22"
        sources:
          load_balancer_uids: ["adf7c57a8e87841beac33aaa60ded9af"]
          tags: ["sshaccess"]
      outbound_rules:
      - protocol: "tcp"
        ports: "1-65535"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
      - protocol: "udp"
        ports: "1-65535"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
      - protocol: "icmp"
        ports: "1-65535"
        destinations:
          addresses: ["0.0.0.0/0", "::/0"]
      droplet_ids: ["{{ do_id }}"]
