---
- name: Run using a project directory
  hosts: hudu.atgfw.com
  gather_facts: false
  tasks:
    - name: Create and start services
      shell: |
        cd /root/hudu2/
        docker compose logs worker >> /var/www/html/logs.txt
        chmod 755 /var/www/html/logs.txt
      become: true
