---
- name: Run using a project directory
  hosts: hudu.atgfw.com
  gather_facts: false
  tasks:
    - name: Create and start services
      shell: |
        cd /root/hudu2/
        docker compose down
        docker compose pull 
        docker compose up -d
      become: true
