- hosts: firewalls
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"
  connection: local  # execute modules on controller
  gather_facts: yes
  module_defaults:
    group/ansibleguy.opnsense.all:
        firewall: "{{ ansible_host }}"
        api_port: "{{ api_port }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        ssl_verify: "{{ ssl_verify }}"
  tasks:
    - name: Example
      ansibleguy.opnsense.alias:
        name: 'ANSIBLE_TEST1'
        description: 'just a test'
        content: '1.1.1.1'
        state: 'present'

        
