- hosts: firewalls
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"
  connection: local  # execute modules on controller
  gather_facts: yes
  tasks:
    - name: Example
      ansibleguy.opnsense.alias:
        firewall: "{{ ansible_host }}"
        api_port: "{{ api_port }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        ssl_verify: "{{ ssl_verify }}"
        
